# Generated by Django 6.0.2 on 2026-03-10 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_costo', models.CharField(choices=[('FIJO', 'Fijo'), ('PORCENTAJE', 'Porcentaje')], max_length=15)),
                ('valor_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, help_text='Impuesto en $', max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock disponible')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=200, null=True)),
                ('canal_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.canalventa')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_cliente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_materiales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_canal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ganancia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='gestion.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMaterialProductoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.material')),
                ('producto_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_materiales', to='gestion.productopedido')),
            ],
        ),
    ]
